# ----------------------
# docker-compose.yml
# ----------------------
services:
  mapstitcher:
    container_name: mapstitcher
    build:
      context: .
      dockerfile: Dockerfile_deploy
      args:
        - TAG=v0.0.4
    image: mapstitcher:latest
    environment:
      - MATCHING_ALGORITHM=loftr
      - VRAM_SIZE=8.0
      - OUTPUT_FILE=stitched.jp2
    volumes:
      - ../test_data/:/data  # !adjust!
      - ../output/:/output  # !adjust!
    entrypoint: [ "/app/entrypoint_oneshot.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: no


  mapstitcher_service:
    container_name: mapstitcher_service
    image: mapstitcher:latest
    environment:
      - MATCHING_ALGORITHM=loftr
      - VRAM_SIZE=8.0
      - OUTPUT_FILE=stitched.jp2
    volumes:
      - ../test_data/:/data  # !adjust!
      - ../output/:/output  # !adjust!
    entrypoint: [ "/app/entrypoint_service.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: no
